# Generated by Django 4.1.3 on 2022-12-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authentication',
        ),
    ]
